# Generated by Django 6.0.1 on 2026-01-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='About Me', max_length=200)),
                ('description', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=300)),
                ('button_text', models.CharField(default='Contact Me', max_length=50)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
            ],
        ),
    ]
